### PR TITLE
Issue #77: Save editor configuration settings in browser

### LINKED ISSUE #77: Save editor configuration settings in browser
This way returning users will have the same editor settings they had on their last visit.

### PR DESCRIPTION
**Pull request by wchill**
To save settings, I initialize the browser's local storage (after first checking if it's supported) and read/write to it upon setting changes. If local storage is not supported, then we just use default settings like before.

Closes #77.

### CODE REVIEW

**Comment by wchill** [comment]
Looks like there's some jshint failures, fixing.

**Comment by neelabhg** [comment]
As discussed in the team chat group, it seems like a good idea to encapsulate user settings in some kind of "preference service". In the future, other settings not necessarily belonging to the editor will be saved, such as disabling notification popups as mentioned by @scowalt, etc.

Also, the local storage keys should be namespaced to avoid conflicts. A separate module for handling preferences will be beneficial for this, as it could control the key names and could, for example, prefix the object name which stored the key, etc.

**Comment by wchill** [comment]
All Local Storage code has been refactored into `preferences.js`. Rudimentary, but functional, namespacing support is provided by a wrapper class called `NamedPreferences` which prepends the namespace automatically when performing any Local Storage operations.

**Comment by anant-singh** [comment]
I went through the `preferences.js`. The implementation looks good to me.

**Comment by wchill** [comment]
@neelabhg can you merge + close?

**Pull request merged**
